name: CI
on:
  push:
    branches:
      - main
jobs:
  notify-slack-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack Channel of Merge
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02QC1HUDHT'
          slack-message: 'Merge of changes completed. "\n"${{github.event.compare}}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACKSECRETNOFITYKEY }}
