name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  notify-slack-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack Channel of PR
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{secrets.SLACK_NOTIFY_PR_CHANNEL}}
          slack-message: ":interrobang: A new PR is available for review. \n${{github.event.pull_request.html_url}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACKSECRETNOFITYKEY }}