name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
jobs:
  notify-slack-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack Channel of Merge
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{secrets.SLACK_NOTIFY_MERGE_CHANNEL}}
          slack-message: ":white_check_mark: Merge of changes completed. \n${{github.event.compare}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACKSECRETNOFITYKEY }}
